"""Prompt templates for transformer diagnostics and assessment."""

_INTERPRET_DGA_PROMPT = (
    "You are a transformer diagnostic expert. Analyse the following "
    "dissolved gas analysis (DGA) readings for asset {asset_name} "
    "and determine the fault type using IEC 60599 ratio method.\n\n"
    "DGA Readings:\n"
    "  Hydrogen (H2):    {hydrogen} ppm\n"
    "  Methane (CH4):    {methane} ppm\n"
    "  Acetylene (C2H2): {acetylene} ppm\n"
    "  Ethylene (C2H4):  {ethylene} ppm\n"
    "  Ethane (C2H6):    {ethane} ppm\n\n"
    "Steps to follow:\n"
    "1. Compute R1=CH4/H2, R2=C2H2/C2H4, R3=C2H4/C2H6\n"
    "2. Convert to IEC codes:\n"
    "   R1: <0.1->0, 0.1-3->1, >3->2\n"
    "   R2: <0.1->1, 0.1-1->0, >1->2\n"
    "   R3: <1->0, 1-3->1, >3->2\n"
    "3. Map code combination to fault type:\n"
    "   (0,0,0)->NF, (0,1,0)->PDLED, (1,1,0)->PDHED,\n"
    "   (1or2,0,1or2)->LED, (1,0,2)->HED,\n"
    "   (0,0,1)->LTH1, (0,2,0)->LTH4, (0,2,1)->MTH,\n"
    "   (0,2,2)->HTH, other->UD\n"
    "4. Recommend an action.\n\n"
    "Respond in exactly this format:\n"
    "Fault Type: <fault type>\n"
    "R1 (CH4/H2): <value>\n"
    "R2 (C2H2/C2H4): <value>\n"
    "R3 (C2H4/C2H6): <value>\n"
    "Code (R1,R2,R3): <code combination>\n"
    "Confidence: <High|Medium|Low>\n"
    "Reasoning: <one sentence>\n"
    "Recommended Action: <action>"
)

_ASSESS_WINDING_PROMPT = (
    "You are a transformer thermal assessment expert. Evaluate the "
    "winding temperature condition of asset {asset_name} using "
    "IEC 60076-7.\n\n"
    "Temperature Readings:\n"
    "  Winding Temperature (WTI): {wti} C\n"
    "  Oil Temperature (OTI):     {oti} C\n"
    "  Ambient Temperature (ATI): {ati} C\n"
    "  Alarm flag (OTI_A):        {oti_a}\n"
    "  Trip flag (OTI_T):         {oti_t}\n\n"
    "Steps to follow:\n"
    "1. Compute hot-spot rise = WTI - ATI.\n"
    "2. Thermal status: <=98C Normal, <=140C Warning, "
    "<=160C Critical, >160C or trip=1 Trip.\n"
    "3. Ageing rate = 2^((WTI-98)/6).\n"
    "4. Check alarm and trip flags.\n"
    "5. Recommend an action.\n\n"
    "Respond in exactly this format:\n"
    "Thermal Status: <Normal|Warning|Critical|Trip>\n"
    "Hot-Spot Rise (C): <value>\n"
    "Ageing Rate: <value>\n"
    "Alarm Active: <Yes|No>\n"
    "Trip Active: <Yes|No>\n"
    "Risk Level: <Low|Medium|High|Critical>\n"
    "Reasoning: <one sentence>\n"
    "Recommended Action: <action>"
)

_ASSESS_LOAD_PROMPT = (
    "You are a transformer load assessment expert. Evaluate the "
    "loading condition of asset {asset_name}.\n\n"
    "Electrical Readings:\n"
    "  Phase voltages: VL1={vl1}V, VL2={vl2}V, VL3={vl3}V\n"
    "  Phase currents: IL1={il1}A, IL2={il2}A, IL3={il3}A\n"
    "  Line voltages:  VL12={vl12}V, VL23={vl23}V, VL31={vl31}V\n"
    "  Neutral current: INUT={inut}A\n"
    "  Rated Capacity: {rated_mva} MVA\n\n"
    "Steps to follow:\n"
    "1. load_mva = (VL12*IL1+VL23*IL2+VL31*IL3)/(sqrt(3)*1e6)\n"
    "2. load_factor_pct = (load_mva/rated_mva)*100\n"
    "3. <=100% Normal, <=110% Overloaded, >110% Severely Overloaded\n"
    "4. imbalance = (max-min)/mean of IL1,IL2,IL3 * 100\n"
    "5. INUT > 10% of mean phase current indicates imbalance.\n"
    "6. Recommend an action.\n\n"
    "Respond in exactly this format:\n"
    "Load MVA: <value>\n"
    "Load Factor (%): <value>\n"
    "Loading Status: <Normal|Overloaded|Severely Overloaded>\n"
    "Current Imbalance (%): <value>\n"
    "Neutral Current Flag: <Yes|No>\n"
    "Reasoning: <one sentence>\n"
    "Recommended Action: <action>"
)