"""Prompt templates used by the scenario-generation pipeline."""

from .asset_profile import PROFILE_BUILDER_PROMPT
from .budget import BUDGET_ALLOCATOR_PROMPT
from .generation import (
    MULTIAGENT_COMBINER_PROMPT,
    SCENARIO_GENERATOR_PROMPT,
    VALIDATE_REPAIR_PROMPT,
)
from .research_digest import (
    RESEARCH_DIGEST_HEADINGS_MARKDOWN,
    RESEARCH_DIGEST_MERGE_HEADINGS_MARKDOWN,
    RESEARCH_DIGEST_MERGE_SECTION_HEADINGS,
    RESEARCH_DIGEST_SECTION_HEADINGS,
    RESEARCH_MERGE_PROMPT,
    RESEARCH_PER_PAPER_PROMPT,
)
from .retrieval import (
    RETRIEVAL_METADATA_JUDGE_PROMPT,
    RETRIEVAL_QUERY_PLAN_PROMPT,
    RETRIEVAL_QUERY_PLAN_PROMPT_SECTION,
)

__all__ = [
    "BUDGET_ALLOCATOR_PROMPT",
    "MULTIAGENT_COMBINER_PROMPT",
    "PROFILE_BUILDER_PROMPT",
    "RESEARCH_DIGEST_HEADINGS_MARKDOWN",
    "RESEARCH_DIGEST_MERGE_HEADINGS_MARKDOWN",
    "RESEARCH_DIGEST_MERGE_SECTION_HEADINGS",
    "RESEARCH_DIGEST_SECTION_HEADINGS",
    "RESEARCH_MERGE_PROMPT",
    "RESEARCH_PER_PAPER_PROMPT",
    "RETRIEVAL_METADATA_JUDGE_PROMPT",
    "RETRIEVAL_QUERY_PLAN_PROMPT",
    "RETRIEVAL_QUERY_PLAN_PROMPT_SECTION",
    "SCENARIO_GENERATOR_PROMPT",
    "VALIDATE_REPAIR_PROMPT",
]
